### ISSUE TITLE
Download Link to Pre-Build Image Broken

### ISSUE THREAD

**Issue by LaughingOakFarm** [maxvfischer/sonos-streaming#2]
The link points to here: https://github.com/maxvfischer/sonos-streaming/suites/17721720018/artifacts/1014666374

But it seems to result in a 404. Any ideas, I see your GitHub Actions workflow to build it, but I don't see where the image is saved.

**Comment by LaughingOakFarm** [comment]
Nevermind, it is working now. I can't explain that.

**Comment by AmpersandCastle** [comment]
I was getting the same problem, logging into my github account seems to have solved it.
