### ISSUE TITLE
License and usage of your work

### ISSUE THREAD

**Issue by aleksanderbl29** [maxvfischer/sonos-streaming#3]
Hi @maxvfischer 

I am currently trying to build a docker image to do what your docker-compose file does with combining the softwares.
May I borrow some of your configs if I refer back to this repo?

I don't see a license in the repo and thought I'd reach out and ask :)

Thank you in advance!

**Comment by maxvfischer** [comment]
Hey, thanks for reaching out! 

Feel free to do whatever you want with the code 😄 Thanks for pointing out that I forgot to add a license, will add!

**Comment by aleksanderbl29** [comment]
Thanks a lot! Great work you have done here. Got it to work in literal minutes🫡
