### ISSUE TITLE
Updates for the TuneIn (new) App

### ISSUE THREAD

**Issue by sidens** [maxvfischer/sonos-streaming#4]
Hi Max - love this guide & been using the setup successfully for a few months. Found this post in the sonos community with support for the TuneIn (new) app. Sharing here in case it's helpful for others!
https://en.community.sonos.com/using-sonos-with-a-turntable-229138/custom-local-tune-in-urls-not-supported-in-the-new-app-6892871

**Comment by maxvfischer** [comment]
Hey! Glad you like it and thanks for sharing! I also noticed a while back that the stream stopped working and that they'd updated the app. I also managed to solve it, but just haven't got to updating the guide yet. Thanks for the push to do it! 

I'm currently abroad until the end of the month, but will update the guide when I'm back :)

**Comment by maxvfischer** [comment]
Hi again @sidens . I've now updated the README using the new TuneIn app. Thanks for pushing me to do this :)
