### ISSUE TITLE
Artifact Link Not Working

### ISSUE THREAD

**Issue by FlyingSkullGames** [maxvfischer/sonos-streaming#5]
Whenever you click the link for the image, github says it failed to generate url to download image

**Comment by maxvfischer** [comment]
Hey! Ah, the artifact has expired. Tried to rerun the workflow to generate a new image, but got an error. Will look into it when I have time.

If you want to get it up and running right now, you can do the following:
1. Install a default base RPi image through `Raspberry Pi Imager`
2. Clone down this repo on the RPi
3. Run: `./install_docker.sh`
4. Start service: `docker compose up -d`

If you also want to setup a service to automatically start it on boot, you can check out `setup-service.sh`.

I will fix and generate a new image when I have time :)

**Comment by maxvfischer** [comment]
Hi again @FlyingSkullGames . I've now fixed the pipeline and updated the README with the new links. You can find the image here: https://github.com/maxvfischer/sonos-streaming/actions/runs/10234626939/artifacts/1773367264

**Comment by ABested** [comment]
Hi @maxvfischer 
The link seems to have expired again. Would you be able to make a release of the image?
In the meantime, ill try cloning the repo as described above

**Comment by maxvfischer** [comment]
Hey @ABested , 
I really need to switch to a better hosting of the image 🤦‍♂️ . 

I've re-triggered the workflow. When done you should be able to see it at the bottom of the page here, under `Artifacts`: https://github.com/maxvfischer/sonos-streaming/actions/runs/12058015195

**Comment by maxvfischer** [comment]
@ABested here is the newly build image: https://github.com/maxvfischer/sonos-streaming/actions/runs/12058015195/artifacts/2246853310

**Comment by ABested** [comment]
@maxvfischer Thank you! I think I've gotten it up and running (Just need to dust off my record player for testing)

**Comment by cThumbs226** [comment]
Hi @maxvfischer,
The link, even the one above in this chat from two weeks ago seems to have expired. I built the original instructables build years ago and just moved and was looking to build it fresh, but was agonising about how much simpler it could be. So glad to see someone with the skills to actually make it simpler has done this! Thanks!

**Comment by maxvfischer** [comment]
@cThumbs226 Thanks for your kind words, really appreciate it! Just glad that the time I spend setting it up helps other people 😄 

> The link, even the one above in this chat from two weeks ago seems to have expired.

That's strange, when I click the link above (https://github.com/maxvfischer/sonos-streaming/actions/runs/12058015195/artifacts/2246853310), it prompts a download of the image for me. Shouldn't matter, but what browser are you using?

**Comment by ChimorinNL** [comment]
Hi! The build has expired, could you make a new one?

**Comment by maxvfischer** [comment]
@ChimorinNL It's still working, think I just fucked up the linking in the README. Try this: https://github.com/maxvfischer/sonos-streaming/actions/runs/12058015195/artifacts/2246853310

Haha but this is unfeasible. I'll try to make time this weekend to trigger the job on cron instead.

**Comment by wilksnup** [comment]
Hi, build has expired, could we get a new one? Thank you for this guide!

**Comment by maxvfischer** [comment]
@wilksnup I've triggered a new workflow here: https://github.com/maxvfischer/sonos-streaming/actions/runs/13652358409. Will update the README as well with the new link, but if you want to access the image before that, you can download the artifact (image) at the bottom of the linked page, when the run is done.

I also spent a bit of time this weekend to start migrating to using Releases, instead of `Actions artifacts`. That should solve the retention issue.

**Comment by maxvfischer** [comment]
@wilksnup I've now updated the link in the README
